builds:
  - 
    ldflags:
      - -X github.com/NodyHub/fifi.version={{.Version}
      - -X github.com/NodyHub/fifi.commit={{.Commit}}
      - -X github.com/NodyHub/fifi.date={{.CommitDate}}
      - -X github.com/NodyHub/fifi.builtBy=goreleaser-action
    env:
        - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
